// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsigyfoswkounxmkyinm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaWd5Zm9zd2tvdW54bWt5aW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTQxNzIsImV4cCI6MjA2NDc3MDE3Mn0.0bFa9v_A1ebeVSzC_M1Q8Czg3oy2kLKvC_P5kLNDRrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);